application offline payments
Transerve-PwC/municipal-services pull request #112
Opened 2020-10-22 12:47 UTC by vinil-transerve

2020-10-22 14:54 UTC, rajiv-transerve requested changes

2020-10-22 14:54 UTC, rajiv-transerve commented on estate-services/src/main/java/org/egov/ps/config/Configuration.java
> +	private String billGenearateEndpoint;
Change to `billGenerateEndpoint`

2020-10-22 14:54 UTC, rajiv-transerve commented on estate-services/src/main/java/org/egov/ps/service/ApplicationService.java
> +		application.setOfflinePaymentDetails(Collections.singletonList(offlinePaymentDetails));
To be removed

2020-10-22 14:54 UTC, rajiv-transerve commented on estate-services/src/main/java/org/egov/ps/validator/ApplicationValidatorService.java
> +	public ApplicationCriteria getApplicationCriteria(ApplicationRequest request) {
revert

2020-10-23 06:01 UTC, rajiv-transerve requested changes

2020-10-23 06:01 UTC, rajiv-transerve commented on estate-services/src/main/java/org/egov/ps/controller/ApplicationController.java
> +	@PostMapping("/_offlinepayment")
Change this to `_collect_payment` and make sure only employees can access these requests in MDMS.

2020-10-23 06:01 UTC, rajiv-transerve commented on estate-services/src/main/java/org/egov/ps/model/Application.java
> +	private List<OfflinePaymentDetails> offlinePaymentDetails;
This should not be there. As mentioned yesterday, there will only ever be a single payment.

2020-10-23 06:01 UTC, rajiv-transerve commented on estate-services/src/main/java/org/egov/ps/model/OfflinePaymentDetails.java
> +package org.egov.ps.model;
This file can be retained but only to be used for collecting offline rent for properties not application offline payment.

2020-10-23 06:01 UTC, rajiv-transerve commented on estate-services/src/main/java/org/egov/ps/model/Application.java
> +	private String paymentConsumerCode;
There should be no new paymentConsumerCode for an application. The application number should be used to generated demand, bill etc..

2020-10-23 06:05 UTC, vinil-transerve commented on estate-services/src/main/java/org/egov/ps/model/Application.java
> +	private List<OfflinePaymentDetails> offlinePaymentDetails;
yes, sorry, I will do it know

2020-10-23 06:06 UTC, vinil-transerve commented on estate-services/src/main/java/org/egov/ps/config/Configuration.java
> +	private String billGenearateEndpoint;
done

2020-10-23 06:06 UTC, vinil-transerve commented on estate-services/src/main/java/org/egov/ps/service/ApplicationService.java
> +		application.setOfflinePaymentDetails(Collections.singletonList(offlinePaymentDetails));
done

2020-10-23 06:06 UTC, vinil-transerve commented on estate-services/src/main/java/org/egov/ps/validator/ApplicationValidatorService.java
> +	public ApplicationCriteria getApplicationCriteria(ApplicationRequest request) {
done

2020-10-23 06:06 UTC, vinil-transerve commented on estate-services/src/main/java/org/egov/ps/controller/ApplicationController.java
> +	@PostMapping("/_offlinepayment")
done

2020-10-23 09:41 UTC, merged