number validation added for property and ownership transfer
Transerve-PwC/municipal-services pull request #128
Opened 2020-10-28 05:13 UTC by Transerveshivam

2020-10-28 09:01 UTC, rajiv-transerve requested changes

2020-10-28 09:01 UTC, rajiv-transerve commented on rented-properties/src/main/java/org/egov/cpt/validator/PropertyValidator.java
> +	public void validateNumericValueForOwnershipTransfer(OwnershipTransferRequest request) {
Please rename to `validatePropertyRentDetails`

2020-10-28 09:29 UTC, Transerveshivam commented on rented-properties/src/main/java/org/egov/cpt/validator/PropertyValidator.java
> +	public void validateNumericValueForOwnershipTransfer(OwnershipTransferRequest request) {
method name changed

2020-10-29 13:18 UTC, rajiv-transerve approved these changes

2020-10-29 13:19 UTC, merged